Header    header

uint8    current_task
float32  speed
float32  radius
float32  odom_x
float32  odom_y
float32  odom_angle
float32  odom_radius
float32  odom_speed_x
float32  odom_speed_y
uint16   battery_capacity
uint16   battery_current
uint16   battery_voltage
int32    warning_code
uint8    crossSensorValue
float32  ultrasonicValue
int32    error_code
uint8    charge_state
float32  putter_height


